/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/packages/animations/src/animation_metadata.ts:

/** @typedef {?} */
var AnimateTimings;
/**
 * @record
 * @struct
 */
function AnimationOptions() {}
 /** @type {?} */
AnimationOptions.prototype.delay;
 /** @type {?} */
AnimationOptions.prototype.params;
/**
 * @extends {AnimationOptions}
 * @record
 * @struct
 */
function AnimateChildOptions() {}
 /** @type {?} */
AnimateChildOptions.prototype.duration;
/**
 * @extends {AnimationOptions}
 * @record
 * @struct
 */
function AnimationQueryOptions() {}
 /** @type {?} */
AnimationQueryOptions.prototype.optional;
 /** @type {?} */
AnimationQueryOptions.prototype.limit;
