/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/sandbox/processwrapper-sandbox/368/execroot/angular/packages/animations/src/animation_metadata.ts:
/** @const */
var angular$packages$animations$src$animation_metadata = {};

/** @typedef {?} */
angular$packages$animations$src$animation_metadata.AnimateTimings;
/**
 * @record
 * @struct
 */
angular$packages$animations$src$animation_metadata.AnimationOptions = function() {};
/** @type {?|undefined} */
angular$packages$animations$src$animation_metadata.AnimationOptions.prototype.delay;
/** @type {?|undefined} */
angular$packages$animations$src$animation_metadata.AnimationOptions.prototype.params;
/**
 * @extends {angular$packages$animations$src$animation_metadata.AnimationOptions}
 * @record
 * @struct
 */
angular$packages$animations$src$animation_metadata.AnimateChildOptions = function() {};
/** @type {?|undefined} */
angular$packages$animations$src$animation_metadata.AnimateChildOptions.prototype.duration;
/**
 * @extends {angular$packages$animations$src$animation_metadata.AnimationOptions}
 * @record
 * @struct
 */
angular$packages$animations$src$animation_metadata.AnimationQueryOptions = function() {};
/** @type {?|undefined} */
angular$packages$animations$src$animation_metadata.AnimationQueryOptions.prototype.optional;
/** @type {?|undefined} */
angular$packages$animations$src$animation_metadata.AnimationQueryOptions.prototype.limit;
